Template match fixes to add screenshot path definition
testdevlab/Py-TestUI pull request #46
Opened 2023-01-26 13:12 UTC by alvarolaserna

2023-05-02 15:13 UTC, paulsgrudups requested changes

2023-07-13 08:03 UTC, alvarolaserna commented on testui/elements/testui_element.py
> +            print(top_left.x, top_left.y, dimensions.x, dimensions.y)
Made it as a debug log instead of print

2023-07-13 08:03 UTC, alvarolaserna commented on tests/appium_tests.py
> +            # .set_screenshot_path("report_screenshots")
I've removed this

2023-07-13 08:03 UTC, alvarolaserna commented on testui/support/testui_images.py
> +    logger.log(root_dir)
done

2023-07-13 08:33 UTC, paulsgrudups approved these changes

2023-07-13 08:33 UTC, merged